path:
  ckpt_path: "./GiuliaAI/model/v1/output/ckpt/GiuliaAI-24-07-26"
  log_path: "./GiuliaAI/model/v1/output/log/GiuliaAI-24-07-26"
  result_path: "./GiuliaAI/model/v1/output/result/GiuliaAI-24-07-26"
optimizer:
  batch_size: 6
  betas: [0.9, 0.98]
  init_lr: 0.0002
  gamma: 0.97565
  eps: 0.000000001
  weight_decay: 0.0
  grad_clip_thresh: 1.0
  grad_acc_step: 6
  warm_up_step: 4000
  anneal_steps: []
  anneal_rate: 1.0
  bin_loss_start_epoch: 100
  bin_loss_warmup_epochs: 40
step:
  total_step: 900000
  log_step: 100
  synth_step: 100
  val_step: 10000
  save_step: 100

